config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  # root "application#hello"
  resources :quizzes do
    member do
      get 'overview'
    end
    resources :questions, only: [:index, :create, :edit, :update, :destroy, :show] do
      member do
        get 'answer'
        get 'result'
        get 'confirm_destroy'
        delete :destroy # destroyアクションのルーティング
      end
    end
    member do
      get 'confirm_destroy' # クイズ削除確認ページ
    end
  end
  resources :choices
  resources :users, only: [:index, :show]
  resources :user_questions, only: [:create]
  resources :quizzes do
    resource :favorites, only: [:create, :destroy] # create と destroy を指定
  end

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  root "sessions#new"
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :choices, dependent: :destroy
    belongs_to :quiz
    belongs_to :point, optional: true
    accepts_nested_attributes_for :choices, allow_destroy: true
    has_many :user_questions
    validates :content, presence: true, length: { minimum: 1, maximum: 50 }
    validates :supplement, length: { minimum: 1, maximum: 50 }, allow_blank: true
    validates :point_id, presence: { message: "を選択してください" }
    validate :validate_choices
    validate :validate_correct_choice
  
    def validate_choices
      if choices.length < 2
        errors.add(:choices, "は2つ以上必要です")
      end
      if choices.any? { |choice| choice.name.blank? || choice.name.length > 50 }
        errors.add(:choices, "の内容は1文字以上50文字以内で入力してください")
      end
    end
  
    def validate_correct_choice
      if choices.none?(&:is_valid)
        errors.add(:correct_choice, "を1つ選択してください")
      end
    end
  end
  

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @quiz = Quiz.find(params[:quiz_id])
        @questions = @quiz.questions.includes(:choices)
        @user = current_user
        @current_score = @user.total_points if @user

        # 特定の設問を表示するためのロジックを追加
        if params[:question_id]
            @current_question = Question.find(params[:question_id])
        end
    end


    def answer
        @question = Question.find(params[:id])
        @user = current_user # ユーザー情報を取得

        # ユーザーの回答を取得
        @user_question = UserQuestion.where(user_id: @user.id, question_id: @question.id).order(created_at: :desc).first

        @user_answer = @user_question.result # user_questionsテーブルのresultカラムの値を取得

        @explanation = @question.supplement # 質問の解説を取得
        Rails.logger.debug("User Questionだよ: #{@user_question}")
        Rails.logger.debug("User Answerだよ: #{@user_question.result}")

        # answer.html.erb ビューを表示
        render 'answer'
    end

    def confirm_destroy
        @question = Question.find(params[:id])
        @quiz = @question.quiz # 削除する設問が属するクイズを取得
    end

    def destroy
        @question = Question.find(params[:id])
        quiz = @question.quiz # 削除する設問が属するクイズを取得

        if @question.destroy
            # 削除後にクイズ内の設問が残っているか確認
            if quiz.questions.count == 0
                quiz.destroy # 設問が残っていなければクイズを削除
                redirect_to quizzes_path, notice: 'クイズが削除されました！'
            else
                redirect_to quizzes_path, notice: '質問が削除されました！'
            end
        else
            redirect_to quizzes_path, alert: '質問の削除に失敗しました。'
        end
    end

    def update
        @quiz = Quiz.find(params[:quiz_id])
        @question = @quiz.questions.find(params[:id])
        Rails.logger.debug("Received: #{params.inspect}")
        if @question.update(question_params)
            render json: { message: '設問が更新されました。' }, status: :ok
        else
            render json: { error: '設問の更新に失敗しました。' }, status: :unprocessable_entity
        end
    end

    def show
        @question = Question.find(params[:id]) # ここで質問を取得
        @user = current_user # ユーザー情報を取得
        @quiz = Quiz.find(params[:quiz_id])
        @questions = @quiz.questions.includes(:choices)
        @current_score = @user.total_points if @user
        @quiz_questions = @question.quiz.questions
        @question_index = @quiz_questions.index(@question) + 1 # 1から始まる番号にするために +1

        # 特定の設問を表示するためのロジックを追加
        if params[:question_id]
            @current_question = Question.find(params[:question_id])
        end
    end

    def result
        @quiz = Quiz.find(params[:quiz_id])
        @user = current_user

        @user_questions = UserQuestion.where(user_id: @user.id, question_id: @quiz.questions.pluck(:id))
                                      .order(created_at: :desc)
                                      .limit(@quiz.questions.count)

        # resultがtrueのものの数をカウント
        @correct_answers = @user_questions.select(:result).count { |uq| uq.result == true }

        # 総設問数を取得
        @total_questions = @quiz.questions.count

        Rails.logger.debug("User Questions: #{@user_questions.inspect}")
        Rails.logger.debug("Correct Answers Count: #{@correct_answers_count}")

        # 最初の設問を取得
        @first_question = @quiz.questions.first
    end

    private

    def question_params
        params.require(:question).permit(
            :content, :supplement,
            choices_attributes: [:id, :name, :is_valid, :_destroy]
        )
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/answer.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>解説</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F4F9F8; /* 明るい背景色 */
            color: #333333;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        p {
            font-size: 1.2rem;
            margin: 15px 0;
        }

        .btn {
            background-color: #3DB8A4; /* ボタンの色 */
            color: white;
            padding: 12px 25px;
            border: none;
            border-radius: 8px;
            font-size: 1.2rem;
            cursor: pointer;
            transition: background-color 0.3s ease;
            text-decoration: none;
            display: inline-block;
            margin: 20px;
        }

        .btn:hover {
            background-color: #339D88; /* ホバー時の色 */
        }

        .btn-primary {
            background-color: #3DB8A4;
        }

        .btn-primary:hover {
            background-color: #339D88;
        }

        h2 {
            font-size: 1.5rem;
            color: #3DB8A4; /* Green-100色 */
            margin-top: 40px;
        }

        .content-container {
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .result-message {
            font-size: 1.2rem;
            margin: 20px 0;
            padding: 10px;
            border-radius: 5px;
        }

        .correct {
            background-color: #E0F8F0; /* 正解の背景色 */
            color: #1A7F56;
        }

        .incorrect {
            background-color: #FFEBEB; /* 不正解の背景色 */
            color: #D9534F;
        }

        .correct-answer {
            font-weight: bold;
            color: #1A7F56; /* 正解の色 */
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="content-container">
        <p class="text-3xl font-bold leading-normal">質問：<%= @question.content %></p>

        <div class="result-message <%= @user_answer == true ? 'correct' : 'incorrect' %>">
            <p>あなたの回答: <%= @user_answer == true ? '正解' : '不正解' %></p>

            <% if @user_answer == true %>
                <p>おめでとうございます！正解です。</p>
            <% else %>
                <p>残念ながら不正解です。もう一度挑戦してください。</p>
            <% end %>
        </div>

        <!-- 正解の選択肢を表示 -->
        <p class="correct-answer">正解の選択肢:
            <%= @question.choices.find_by(is_valid: true).name %>
        </p>

        <h2>解説・参考</h2>
        <p><%= @explanation %></p>

        <% next_question = @question.quiz.questions.where("id > ?", @question.id).first %>
        <% if next_question %>
            <%= link_to '次の質問へ', quiz_question_path(@question.quiz_id, next_question.id), class: 'btn btn-primary' %>
        <% else %>
            <p>これが最後の質問です。</p>
            <%= link_to '結果を確認する', result_quiz_question_path(@question.quiz_id), class: 'btn btn-primary' %>
        <% end %>
    </div>
</body>

</html>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
</head>

<body class="font-noto">

    <div class="bg-[url('bg-hero.png')] bg-center bg-contain bg-no-repeat text-white font-bold pt-40 pb-10">
        <div class="ml-10">
            <p class="text-lg mx-auto">
                POSSE課題
            </p>
            <p class="text-6xl mt-3 mb-40">
                ITクイズ
            </p>
        </div>
    </div>
    <main class="w-5/6 mx-auto">
        <div id="quiz-container">
            <% @questions.each_with_index do |question, index| %>
                <div class="w-full mb-32" data-quiz-id="<%= question.id %>">
                    <p class="bg-[#0071bc] rounded-lg text-white text-3xl w-20 h-16 font-bold mb-6 flex justify-center items-center">Q<%= index + 1 %></p>
                    <p class="text-xl font-bold mt-4">ポイント: <%= question.point.point %> pt</p>
                    <p class="text-3xl font-bold leading-normal"><%= question.content %></p>
                    <% if question.image.is_a?(ActiveStorage::Attached::One) && question.image.attached? %>
                        <%= image_tag question.image, alt: "milmil", class: "w-1/5" %>
                    <% else %>
                        <%= image_tag 'quiz02.png', alt: 'default image', class: 'w-1/5' %> <!-- デフォルト画像 -->
                    <% end %>
                    <div class="w-full my-8 flex justify-center gap-4">
                        <% question.choices.each do |choice| %>
                            <%= form_with url: answer_quiz_question_path(question.quiz_id, question.id), method: :post, local: true do %>
                                <p class="choice w-1/3 bg-gray-100 p-4 text-center flex items-center font-bold border-4 rounded-lg border-gray-200 cursor-pointer hidden"
                                    data-is-valid="<%= choice.is_valid %>">
                                    <%= choice.name %>
                                </p>
                                <%= hidden_field_tag "user_question[user_id]", @user['id'] %>
                                <%= hidden_field_tag "user_question[question_id]", question.id %>
                                <%= hidden_field_tag "user_question[result]",  choice.is_valid %>
                                <%= hidden_field_tag "user_question[is_first]", false %>
                                <%= submit_tag choice.name, class: "btn btn-primary" %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="correct hidden">
                        <p class="bg-[#e34e70] rounded-lg text-white text-3xl w-20 h-16 font-bold mb-6 flex justify-center items-center">A</p>
                        <div class=" bg-[rgb(255,242,245)] text-2xl font-bold mt-4 rounded-lg mt-4 px-10 py-6">
                            <p class="text-[rgb(227,78,112)]">正解 !</p>
                            <div class="flex pt-2">
                                <p class="text-xl font-bold">A：</p>
                                <span class="correct_choice text-xl font-bold"></span>
                            </div>
                        </div>
                        <% if question.supplement.present? %>
                        <p class="flex items-center rounded-2xl bg-gray-200 w-full h-20 bg-no-repeat pl-8 font-bold text-lg bg-bottom-[50%] gap-4 mt-2">
                            <%= image_tag "icon-note.png", class: "w-6 py-8" %>
                            <%= question.supplement %>
                        </p>
                        <% end %>
                    </div>
                    <div class="incorrect hidden">
                        <p class="bg-[#e34e70] rounded-lg text-white text-3xl w-20 h-16 font-bold mb-6 flex justify-center items-center">A</p>
                        <div class=" bg-[rgb(233,243,248)] text-2xl font-bold mt-4 rounded-lg mt-4 px-10 py-6">
                            <p class="text-[#0071BC]">不正解 ...</p>
                            <div class="flex pt-2">
                                <p class="text-xl font-bold">A：</p>
                                <span class="correct_answer text-xl font-bold"></span>
                            </div>
                        </div>
                        <% if question.supplement.present? %>
                        <p class="flex items-center rounded-2xl bg-gray-200 w-full h-20 bg-no-repeat pl-8 font-bold text-lg bg-bottom-[50%] gap-4 mt-2">
                            <%= image_tag "icon-note.png", class: "w-6 py-8" %>
                            <%= question.supplement %>
                        </p>
                        <% end %>
                    </div>

                </div>
            <% end %>
        </div>


        <div class="relative mb-36 rounded-[56px] h-96 flex bg-cover bg-center bg-no-repeat bg-[url('bg-line.png')]">
            <div class="absolute inset-0 rounded-[56px] bg-[rgba(0,113,201,0.8)] "></div>
            <div class="flex justify-center absolute gap-4 w-full top-16">
                <%= image_tag "lineicon.png", class: "w-10 h-10 rounded-md" %>
                <h1 class="text-white text-4xl font-bold">POSSE 公式LINE</h1>
            </div>
            <div class="absolute top-32 text-white flex flex-col justify-center font-bold w-full">
                <p class="flex justify-center pb-4">公式LINEにてご質問を随時受け付けております。</p>
                <p class="flex justify-center pb-4">詳細やPOSSE最新情報につきましては、公式LINEにてお知らせ致しますので</p>
                <P class="flex justify-center pb-4">下記ボタンより友達追加をお願いします！</P>
            </div>
            <div>
                <a href="https://line.me/R/ti/p/@651htnqp?from=page" target="_blank" rel="noopener noreferrer" class="block absolute bg-white rounded-[50px] w-1/3 h-12 translate-x-full top-64">
                    <div class="flex justify-center items-center h-full">
                        <p class="mr-2">LINE追加</p>
                        <%= image_tag "icon-link-dark.png", class: "w-3 h-3 right-7 top-0" %>
                    </div>
                </a>
            </div>
        </div>
    </main>
    <footer class="mx-auto">
        <%= image_tag "logo.png", class: "mx-auto" %>
        <div class="text-center mt-6">
            <a href="">POSSE公式サイト</a>
        </div>
        <ul class="flex justify-center mt-4">
            <li class="w-12 h-12 ml-5 rounded-full bg-white shadow-xs border flex justify-center items-center">
                <a href="https://twitter.com/posse_program">
                    <%= image_tag "icon-twitter.png", class: "w-6 h-5" %>
                </a>
            </li>
            <li class="w-12 h-12 ml-4 mr-5 rounded-full bg-white shadow-xs border flex justify-center items-center">
                <a href="https://www.instagram.com/posse_programming/">
                    <%= image_tag "icon-instagram.png", class: "w-6 h-6" %>
                </a>
            </li>
        </ul>
        <div class="text-center mb-8">
            <small>©︎2024 POSSE</small>
        </div>
    </footer>
</body>

</html>

app/views/questions/result.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>結果</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F4F9F8; /* 明るい背景色 */
            color: #333333;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        h1 {
            color: #3DB8A4; /* Green-100色 */
            margin-top: 40px;
            font-weight:bold;
            font-size:32px;
        }

        p {
            font-size: 1.2rem;
            margin: 15px 0;
        }

        .btn {
            background-color: #3DB8A4; /* ボタンの色 */
            color: white;
            padding: 12px 25px;
            border: none;
            border-radius: 8px;
            font-size: 1.2rem;
            cursor: pointer;
            transition: background-color 0.3s ease;
            text-decoration: none;
            display: inline-block;
            margin: 20px;
        }

        .btn:hover {
            background-color: #339D88; /* ホバー時の色 */
        }

        .link {
            color: #3DB8A4; /* Green-100色 */
            font-size: 1rem;
            text-decoration: none;
            transition: color 0.3s ease;
        }

        .link:hover {
            color: #339D88; /* ホバー時の色 */
            text-decoration: underline;
        }

        .content-container {
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin-top: 40px;
        }

        .message {
            font-size: 1.5rem;
            margin-top: 20px;
        }

        .perfect-score {
            background-color: #E0F8F0; /* 正解時の背景色 */
            color: #1A7F56;
            padding: 15px;
            border-radius: 8px;
            font-weight: bold;
        }

        .try-again {
            background-color: #FFEBEB; /* 不正解時の背景色 */
            color: #D9534F;
            padding: 15px;
            border-radius: 8px;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <div class="content-container">
        <h1>結果</h1>
        <p>あなたの正解数: <%= @correct_answers %> / <%= @total_questions %></p>

        <% if @correct_answers == @total_questions %>
            <div class="perfect-score">
                <p>素晴らしい！全問正解です！</p>
            </div>
        <% else %>
            <div class="try-again">
                <p>次回はもっと頑張りましょう！</p>
            </div>
        <% end %>

        <%= link_to '再挑戦する', quiz_question_path(@quiz, @first_question), class: 'btn' %>
        <%= link_to "トップに戻る", quizzes_path, class: "link" %>
    </div>
</body>

</html>

app/views/questions/show.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @question.content %></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <style>
        .btn-choice {
            display: inline-block;
            padding: 14px 28px;
            background-color: #0071bc; /* ボタンの背景色 */
            color: white;
            font-size: 1.25rem;
            font-weight: bold;
            border-radius: 8px; /* 丸みをつける */
            text-align: center;
            cursor: pointer;
            transition: background-color 0.3s ease, transform 0.3s ease;
            width: 600px; /* ボタンの幅を100%に設定 */
            margin-bottom: 12px; /* ボタン間に隙間を追加 */
        }

        .btn-choice:hover {
            background-color: #005a8d; /* ホバー時の色変更 */
            transform: scale(1.05); /* ホバー時に少し大きくなる */
        }

        .btn-choice:active {
            background-color: #004d72; /* クリック時の色変更 */
            transform: scale(0.98); /* クリック時に少し縮む */
        }

        .choice-container {
            display: flex;
            flex-direction: column; /* 縦並びに変更 */
            align-items: center; /* 中央寄せ */
            gap: 12px; /* ボタン間の隙間 */
            width: 100%;
        }
        @media (max-width: 700px) {
            .btn-choice {
                width: 400px; /* 幅を400pxに設定 */
            }
        }

        /* 画面幅400px以下 */
        @media (max-width: 400px) {
            .btn-choice {
                width: 200px; /* 幅を200pxに設定 */
            }
        }
    </style>
</head>

<body class="font-noto">

    <div class="bg-[url('bg-hero.png')] bg-center bg-contain bg-no-repeat text-white font-bold pt-40 pb-10">
        <div class="ml-10">
            <p class="text-6xl mt-3 mb-40">
                <%= @quiz.title %>
            </p>
        </div>
    </div>
    <main class="w-5/6 mx-auto">
        <div id="quiz-container">
            <% if @question.present? %>
                <div class="w-full mb-32" data-quiz-id="<%= @question.id %>">
                    <p class="bg-[#0071bc] rounded-lg text-white text-3xl w-20 h-16 font-bold mb-6 flex justify-center items-center">Q<%= @question_index %></p>
                    <p class="text-xl font-bold mt-4">ポイント: <%= @question.point.point %> pt</p>
                    <p class="text-3xl font-bold leading-normal"><%= @question.content %></p>
                    <div class="choice-container pt-12 pb-12 w-full">
                        <% @question.choices.each do |choice| %>
                            <%= form_with url: user_questions_path, method: :post, local: true do %>
                                <%= hidden_field_tag "user_question[user_id]", @user['id'] %>
                                <%= hidden_field_tag "user_question[question_id]", @question.id %>
                                <%= hidden_field_tag "user_question[result]", choice.is_valid %>
                                <%= hidden_field_tag "user_question[is_first]", false %>
                                <%= submit_tag choice.name, class: "btn-choice" %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% else %>
                <p>質問が見つかりませんでした。</p>
            <% end %>
        </div>
    </main>
</body>

</html>